// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getStandardDeviation
double getStandardDeviation(NumericMatrix img, int u, int v, int n);
RcppExport SEXP _ragram_getStandardDeviation(SEXP imgSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(getStandardDeviation(img, u, v, n));
    return rcpp_result_gen;
END_RCPP
}
// getAverage
double getAverage(NumericMatrix img, int u, int v, int n);
RcppExport SEXP _ragram_getAverage(SEXP imgSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(getAverage(img, u, v, n));
    return rcpp_result_gen;
END_RCPP
}
// getAvgAndSD
NumericVector getAvgAndSD(NumericMatrix img, int u, int v, int n);
RcppExport SEXP _ragram_getAvgAndSD(SEXP imgSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(getAvgAndSD(img, u, v, n));
    return rcpp_result_gen;
END_RCPP
}
// zncc
double zncc(NumericMatrix master, NumericMatrix slave, int u1, int v1, int u2, int v2, int n);
RcppExport SEXP _ragram_zncc(SEXP masterSEXP, SEXP slaveSEXP, SEXP u1SEXP, SEXP v1SEXP, SEXP u2SEXP, SEXP v2SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type master(masterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type slave(slaveSEXP);
    Rcpp::traits::input_parameter< int >::type u1(u1SEXP);
    Rcpp::traits::input_parameter< int >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< int >::type u2(u2SEXP);
    Rcpp::traits::input_parameter< int >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(zncc(master, slave, u1, v1, u2, v2, n));
    return rcpp_result_gen;
END_RCPP
}
// znccMatrix
NumericMatrix znccMatrix(NumericMatrix master, NumericMatrix slave, NumericVector index, int u, int v, int n, NumericVector searchAreaShift);
RcppExport SEXP _ragram_znccMatrix(SEXP masterSEXP, SEXP slaveSEXP, SEXP indexSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nSEXP, SEXP searchAreaShiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type master(masterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type slave(slaveSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type searchAreaShift(searchAreaShiftSEXP);
    rcpp_result_gen = Rcpp::wrap(znccMatrix(master, slave, index, u, v, n, searchAreaShift));
    return rcpp_result_gen;
END_RCPP
}
// disparityMap
NumericVector disparityMap(NumericMatrix master, NumericMatrix slave, NumericVector index, int n, int uStart, int uEnd, int vStart, int vEnd, NumericVector searchAreaShift);
RcppExport SEXP _ragram_disparityMap(SEXP masterSEXP, SEXP slaveSEXP, SEXP indexSEXP, SEXP nSEXP, SEXP uStartSEXP, SEXP uEndSEXP, SEXP vStartSEXP, SEXP vEndSEXP, SEXP searchAreaShiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type master(masterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type slave(slaveSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type uStart(uStartSEXP);
    Rcpp::traits::input_parameter< int >::type uEnd(uEndSEXP);
    Rcpp::traits::input_parameter< int >::type vStart(vStartSEXP);
    Rcpp::traits::input_parameter< int >::type vEnd(vEndSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type searchAreaShift(searchAreaShiftSEXP);
    rcpp_result_gen = Rcpp::wrap(disparityMap(master, slave, index, n, uStart, uEnd, vStart, vEnd, searchAreaShift));
    return rcpp_result_gen;
END_RCPP
}
// znccMultiplied
double znccMultiplied(NumericMatrix master, NumericMatrix slave, int u1, int v1, int u2, int v2, NumericVector n);
RcppExport SEXP _ragram_znccMultiplied(SEXP masterSEXP, SEXP slaveSEXP, SEXP u1SEXP, SEXP v1SEXP, SEXP u2SEXP, SEXP v2SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type master(masterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type slave(slaveSEXP);
    Rcpp::traits::input_parameter< int >::type u1(u1SEXP);
    Rcpp::traits::input_parameter< int >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< int >::type u2(u2SEXP);
    Rcpp::traits::input_parameter< int >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(znccMultiplied(master, slave, u1, v1, u2, v2, n));
    return rcpp_result_gen;
END_RCPP
}
// znccMultipliedMatrix
NumericMatrix znccMultipliedMatrix(NumericMatrix master, NumericMatrix slave, NumericVector index, int u, int v, NumericVector n, NumericVector searchAreaShift);
RcppExport SEXP _ragram_znccMultipliedMatrix(SEXP masterSEXP, SEXP slaveSEXP, SEXP indexSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nSEXP, SEXP searchAreaShiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type master(masterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type slave(slaveSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< int >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type v(vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type searchAreaShift(searchAreaShiftSEXP);
    rcpp_result_gen = Rcpp::wrap(znccMultipliedMatrix(master, slave, index, u, v, n, searchAreaShift));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ragram_getStandardDeviation", (DL_FUNC) &_ragram_getStandardDeviation, 4},
    {"_ragram_getAverage", (DL_FUNC) &_ragram_getAverage, 4},
    {"_ragram_getAvgAndSD", (DL_FUNC) &_ragram_getAvgAndSD, 4},
    {"_ragram_zncc", (DL_FUNC) &_ragram_zncc, 7},
    {"_ragram_znccMatrix", (DL_FUNC) &_ragram_znccMatrix, 7},
    {"_ragram_disparityMap", (DL_FUNC) &_ragram_disparityMap, 9},
    {"_ragram_znccMultiplied", (DL_FUNC) &_ragram_znccMultiplied, 7},
    {"_ragram_znccMultipliedMatrix", (DL_FUNC) &_ragram_znccMultipliedMatrix, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ragram(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
