plotLegend <- function(legend.lab=expression(paste(theta, " [deg]")),
                       zlim=c(0,10),
                       cex=1, cex.axis=1,
                       breaks=NULL, legend.line=2.2,
                       nlevel=18,
                       lab.breaks=c(),                                   
                       horizontal=F,
                       col=colorRampPalette(colors)(nlevel-1), 
                       legend.shrink=1, 
                       legend.width=0.6, 
                       legend.cex=cex,
                       axis.args=list(cex.axis=cex.axis),
                       ...) {
    image.plot(legend.only=TRUE, 
               breaks=breaks,
               zlim=zlim,
               legend.line=legend.line,
               legend.lab=legend.lab,
               nlevel=nlevel, 
               col=col,
               lab.breaks=lab.breaks, 
               horizontal=horizontal, 
               legend.shrink=legend.shrink, 
               legend.width=legend.width, 
               legend.cex=legend.cex,
               axis.args=axis.args,
               ...)
}