# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.getAverage <- function(img, u, v, n) {
    .Call('ragram_getAverage', PACKAGE = 'ragram', img, u, v, n)
}

.getStandardDeviation <- function(img, u, v, n) {
    .Call('ragram_getStandardDeviation', PACKAGE = 'ragram', img, u, v, n)
}

#' Zero normalized cross correlation (ZNCC)
#' 
#' Calculates the zero normalized cross correlation (ZNCC) coefficient between two \code{\link{SAR-class}} objects.
#' This method also works for \code{\link{RasterLayer-class}} objects. The maximum ZNCC value determines disparity.
#'  
#' @export
znccCpp <- function(master, slave, u1, v1, u2, v2, n) {
    .Call('ragram_znccCpp', PACKAGE = 'ragram', master, slave, u1, v1, u2, v2, n)
}

.znccPyramidal <- function(master, slave, u1, v1, u2, v2, n) {
    .Call('ragram_znccPyramidal', PACKAGE = 'ragram', master, slave, u1, v1, u2, v2, n)
}

.getZnccsInSearchArea <- function(master, slave, index, u, v, n, searchAreaShift) {
    .Call('ragram_getZnccsInSearchArea', PACKAGE = 'ragram', master, slave, index, u, v, n, searchAreaShift)
}

.getPyramidalZnccsInSearchArea <- function(master, slave, index, u, v, n, searchAreaShift) {
    .Call('ragram_getPyramidalZnccsInSearchArea', PACKAGE = 'ragram', master, slave, index, u, v, n, searchAreaShift)
}

