# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getStandardDeviationCpp <- function(img, u, v, n) {
    .Call('ragram_getStandardDeviation', PACKAGE = 'ragram', img, u, v, n)
}

#' Window mean written in C++
#' 
#' Calculates window mean for a given \code{\link{SAR-class}} object.
#' The window is a square.
#' 
#' @param object Matrix.
#' @param u Integer. Center of window (column, i.e. y coordinate).
#' @param v Integer. Center of window (row, i.e. x coordinate).
#' @param n Integer. (Window size-1)/2 in x and y direction.
#' @export
getAverageCpp <- function(img, u, v, n) {
    .Call('ragram_getAverage', PACKAGE = 'ragram', img, u, v, n)
}

getAvgAndSDCpp <- function(img, u, v, n) {
    .Call('ragram_getAvgAndSD', PACKAGE = 'ragram', img, u, v, n)
}

#' Zero normalized cross correlation (ZNCC) written in C++
#' 
#' Calculates the zero normalized cross correlation (ZNCC) coefficient between two \code{\link{SAR-class}} objects.
#' This method also works for \code{\link{RasterLayer-class}} objects. The maximum ZNCC value determines disparity.
#'  
#' @param master Matrix.
#' @param slave Matrix.
#' @param u1 Integer. Column, i.e. y coordinate of master pixel.
#' @param v1 Integer. Row, i.e. x coordinate of master pixel.
#' @param u2 Integer. Column, i.e. y coordinate of slave pixel.
#' @param v2 Integer. Row, i.e. x coordinate of slave pixel.
#' @param n Integer. (Window size-1)/2 in x direction.
#' @export
znccCpp <- function(master, slave, u1, v1, u2, v2, n) {
    .Call('ragram_zncc', PACKAGE = 'ragram', master, slave, u1, v1, u2, v2, n)
}

znccMatrixCpp <- function(master, slave, index, u, v, n, searchAreaShift) {
    .Call('ragram_znccMatrix', PACKAGE = 'ragram', master, slave, index, u, v, n, searchAreaShift)
}

disparityMapCpp <- function(master, slave, index, n, uStart, uEnd, vStart, vEnd, searchAreaShift) {
    .Call('ragram_disparityMap', PACKAGE = 'ragram', master, slave, index, n, uStart, uEnd, vStart, vEnd, searchAreaShift)
}

znccMultipliedCpp <- function(master, slave, u1, v1, u2, v2, n) {
    .Call('ragram_znccMultiplied', PACKAGE = 'ragram', master, slave, u1, v1, u2, v2, n)
}

znccMultipliedMatrixCpp <- function(master, slave, index, u, v, n, searchAreaShift) {
    .Call('ragram_znccMultipliedMatrix', PACKAGE = 'ragram', master, slave, index, u, v, n, searchAreaShift)
}

